# This workflow will build a docker container for test

name: Run Dockerfile build test

on:
  workflow_dispatch:

  push:
    paths:
      - "Dockerfile"
      
jobs:
  build-dockerfile:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Dockerfile image
        run: |
          docker build -t captain:alpha-${{ github.sha }} .
